import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Row, Col, Image, Typography, Space, Button } from 'antd'

const { Text } = Typography

//TODO: Fix antd css

export default function Home() {
  return (
    <Row className={styles.container}>
      <Head>
        <title>Sextoy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row>
        <Space>
          <Button>
            SEXTOY SHOP
          </Button>
          <Button>
            ABOUT
          </Button>
          <Button>
            TOKENOMICS
          </Button>
          <Button>
            WHITEPAPER
          </Button>
          <Button>
            ROADMAP
          </Button>
          <Button>
            BSCSCAN
          </Button>
          <Button>
            BUY PANCAKE
          </Button>
        </Space>
      </Row>

      <Row>
        <Text>Play with</Text>
        <Row className={styles.logoContainer}>
          <Image src="/sextoy.png" preview={false} style={{height: '100%', width: '100%'}}/>
        </Row>
      </Row>
    </Row>
  )
}
